### ISSUE TITLE
another release?

### ISSUE THREAD

**Issue by lukebond** [cluster-api-provider-k3s/cluster-api-k3s#40]
would it be possible to do another release and push of the container images? we are using a hand-rolled build to pick up [this fix](https://github.com/cluster-api-provider-k3s/cluster-api-k3s/issues/37) and would like to revert to mainline.

could do it myself if i knew the process!

thanks for the great project :)

**Comment by zawachte** [comment]
Sure. lets do it @ekarlso was working on some automation to build images. Did you get that working?

**Comment by zawachte** [comment]
Ok ill do it manually over the weekend :).

**Comment by zawachte** [comment]
Sorry got a bit delayed here. Working on it.

**Comment by zawachte** [comment]
@lukebond ok its done: https://github.com/cluster-api-provider-k3s/cluster-api-k3s/releases/tag/v0.1.6-hotfix.1

```
ghcr.io/cluster-api-provider-k3s/cluster-api-k3s-bootstrap:v0.1.6-hotfix.1
ghcr.io/cluster-api-provider-k3s/cluster-api-k3s-controlplane:v0.1.6-hotfix.1
```

Huge thanks @ekarlso on the release automation!
