### ISSUE TITLE
Control plane lacks sufficient permissions in tilt as of recent commits

### ISSUE THREAD

**Issue by cannonpalms** [cluster-api-provider-k3s/cluster-api-k3s#45]
The control plane controller starts successfully at 204444b but not b8a4a2176ee01d972708225c23022c45a84b14d4 (HEAD).

It crash loops due to lacking appropriate permissions to populate the controller's informer cache.

Ex:

```
[manager] W0817 16:15:38.835830      14 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.1/tools/cache/reflector.go:169: failed to list *v1beta1.KThreesControlPlane: kthreescontrolplanes.controlplane.cluster.x-k8s.io is forbidden: User "system:serviceaccount:capi-k3s-control-plane-system:default" cannot list resource "kthreescontrolplanes" in API group "controlplane.cluster.x-k8s.io" at the cluster scope
```

**Comment by cannonpalms** [comment]
@ekarlso @zawachte Looks like 7f5c26d inadvertently ripped out pieces of the control plane's ClusterRole.

I don't see `//+kubebuilder:rbac:...` markers in the control plane controller, so I think if in this commit you regenerated manifests from source, it would have had this effect.

That's what I believe would be the proper resolution here: add the missing kubebuilder markers to the control plane controller.

**Comment by zawachte** [comment]
sigh yeap this is the culprit. I guess one of the linters stripped them. Lets get those back in asap.

**Comment by zawachte** [comment]
closing with https://github.com/cluster-api-provider-k3s/cluster-api-k3s/pull/46
