### ISSUE TITLE
CAPV Support

### ISSUE THREAD

**Issue by dipeshtripathi** [cluster-api-provider-k3s/cluster-api-k3s#52]
Really interested in capv as one of the capabilities, saw something being done almost 9 months ago in samples, but not sure if e2e has been setup.
Are there any change of plans for supporting capv?

**Comment by zawachte** [comment]
@ekarlso is running with capv.

**Comment by luisdavim** [comment]
Could you add some samples?

**Comment by luisdavim** [comment]
I've opened this PR to add the CAPV samples: https://github.com/cluster-api-provider-k3s/cluster-api-k3s/pull/74

**Comment by zawachte** [comment]
Closed with https://github.com/cluster-api-provider-k3s/cluster-api-k3s/pull/74
