### ISSUE TITLE
MachineHealthCheck support

### ISSUE THREAD

**Issue by lukebond** [cluster-api-provider-k3s/cluster-api-k3s#63]
this issue is to track support for MachineHealthChecks in cluster-api-provider-k3s.

from the [cluster-api docs](https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/healthchecking.html#limitations-and-caveats-of-a-machinehealthcheck):

---

Before deploying a MachineHealthCheck, please familiarise yourself with the following limitations and caveats:

- Only Machines owned by a MachineSet or a KubeadmControlPlane can be remediated by a MachineHealthCheck (since a MachineDeployment uses a MachineSet, then this includes Machines that are part of a MachineDeployment)
- Machines managed by a KubeadmControlPlane are remediated according to [the delete-and-recreate guidelines described in the KubeadmControlPlane proposal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20191017-kubeadm-based-control-plane.md#remediation-using-delete-and-recreate)
  - The following rules should be satisfied in order to start remediation of a control plane machine:
    - One of the following apply:
      - The cluster MUST not be initialized yet (the failure happens before KCP reaches the initialized state)
      - The cluster MUST have at least two control plane machines, because this is the smallest cluster size that can be remediated.
    - Previous remediation (delete and re-create) MUST have been completed. This rule prevents KCP from remediating more machines while the replacement for the previous machine is not yet created.
    - The cluster MUST have no machines with a deletion timestamp. This rule prevents KCP taking actions while the cluster is in a transitional state.
    - Remediation MUST preserve etcd quorum. This rule ensures that we will not remove a member that would result in etcd losing a majority of members and thus become unable to field new requests (note: this rule applies only to CP already initialized and with managed etcd)
- If the Node for a Machine is removed from the cluster, a MachineHealthCheck will consider this Machine unhealthy and remediate it immediately
- If no Node joins the cluster for a Machine after the NodeStartupTimeout, the Machine will be remediated
- If a Machine fails for any reason (if the FailureReason is set), the Machine will be remediated immediately
---

it is my understanding that we basically need to do what kubeadm does in order to support it, as per guidelines above.

**Comment by mogliang** [comment]
We need this feature. 
I'm quite new for open-source, please let me know how can i contribute on this feature.

**Comment by lukebond** [comment]
> We need this feature. I'm quite new for open-source, please let me know how can i contribute on this feature.

i'm just getting started on taking a shot at it would appreciate your eyes on it when i have something!

**Comment by lukebond** [comment]
fixed in #77 (it's WIP but still counts as a close i think)
