### ISSUE TITLE
Another release?

### ISSUE THREAD

**Issue by lukebond** [cluster-api-provider-k3s/cluster-api-k3s#64]
Feel I'm nagging you about releases sorry, but wanting to get the changes in [this PR](https://github.com/cluster-api-provider-k3s/cluster-api-k3s/pull/59) which includes a regeneration of manifests from a previous PR. I believe the last release is broken without this.

**Comment by zawachte** [comment]
Done with https://github.com/cluster-api-provider-k3s/cluster-api-k3s/releases/tag/v0.1.8
