### ISSUE TITLE
k3s token secret should be the responsibility of the control plane controller

### ISSUE THREAD

**Issue by cannonpalms** [cluster-api-provider-k3s/cluster-api-k3s#69]
https://github.com/cluster-api-provider-k3s/cluster-api-k3s/pull/68 solves the immediate issue of the secret being garbage collected during rollouts, but I don't think it is the right long-term solution.

The token is a concept that exists at the scope of the entire control plane / entire cluster, not the scope of a single machine or machine config.

Forcing the secret to be owned by the Cluster is a step forward, but longer term, I believe that it should be the responsibility of the control plane controller to manage this secret.

**Comment by cannonpalms** [comment]
cc @mogliang

**Comment by mogliang** [comment]
Thanks, i agree.
